### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-MailSystem#1]
I tried to use in the browser [ahnen.hartenthaler.eu/mail-sys/send](https://ahnen.hartenthaler.eu/mail-sys/send), but then I got a JSON response with
```
{
    "users": []
}
```
How can the user / the users be specified?

**Comment by 06Games** [comment]
Hi
Indeed, I forgot to specify in the README that a user list must be passed in the URL (until I find the time to make a configuration page)
You can do something like that: [https://ahnen.hartenthaler.eu/mail-sys/send?users=*USER1*,*USER2*,...](https://ahnen.hartenthaler.eu/mail-sys/send?users=)

Also, I noticed that I forgot to create a new release after my Webtrees 2.1 compatibility commit.
Sorry for the inconvenience.

**Comment by hartenthaler** [comment]
Thank you! Now it is running.
