### ISSUE TITLE
hardcoded/untranslated parts

### ISSUE THREAD

**Issue by HerzScheisse** [06Games/Webtrees-MailSystem#17]
Hey Evan,

First... Many thanks for this awesome modul... i realy like it!

With PR #16 i've provied the german language file for this modul..

And i#ve stumpled upon to parts which are not translated.

First in the modul overview in the admin panel
![wt mailsystem issue 1](https://github.com/06Games/Webtrees-MailSystem/assets/146635896/2f411adf-1c18-47bd-a71f-eb39b361f028)

and then the part of the footer could also be translated... if you have time to work on this...
![wt mailsystem issue 2](https://github.com/06Games/Webtrees-MailSystem/assets/146635896/d0df29ef-f39d-458c-bd84-958c9d8aa9af)

cheers
/Holger

**Comment by 06Games** [comment]
Hi !
First of all, I'd like to thank you for your PR and your feedback.
I have made the necessary changes so that the two texts you mentioned can be translated. If you'd like to modify your PR to include these changes, I'd be delighted to merge it.
