### ISSUE TITLE
not saving config in admin - webtrees clean install 2.0.25 + php7.4

### ISSUE THREAD

**Issue by caww** [06Games/Webtrees-MailSystem#7]
Hello!
Thanks for cool module but not working settings page in admin section
I tried on webtrees 2.1.7 and webtrees 2.0.25 both clean installations
I cant save settings 
But if I adding it using database then module is working and sending emails

**Comment by 06Games** [comment]
Hello,
Indeed, I hadn't noticed that the administration interface was only working with [pretty URLs](https://webtrees.net/faq/urls/).
I should be able to fix that soon.

**Comment by 06Games** [comment]
Fixed in https://github.com/06Games/Webtrees-MailSystem/commit/aa28a4ec76b736a723ad236c70ee2922c16e6aae
