### ISSUE TITLE
Images in email not showing -- maybe better hide it?

### ISSUE THREAD

**Issue by caww** [06Games/Webtrees-MailSystem#8]
Hello!
Thank you - previuos issue fixed very fast! 
please can you fix also images
![image](https://user-images.githubusercontent.com/7277051/198258698-e59ec0f7-5df9-43bf-86eb-4d95387de36c.png)

**Comment by 06Games** [comment]
Hi,
This problem is due to the data url not being supported by all mail clients.
I think I'll add a compatibility mode so that it loads on every client (at the cost of a slight compromise on security since the images will be publicly accessible, although resized to 50x50 px)

**Comment by caww** [comment]
I want to add translate to russian for your mail system
https://disk.yandex.ru/d/WSsG6X3ypUIyWw

**Comment by 06Games** [comment]
Thanks, I added your translation
